### ISSUE TITLE
Investigate Verification of OCSP Response/Signature 

### ISSUE THREAD

**Issue by Tethik** [hbldh/pybankid#5]
See page 27 of docs:
https://www.bankid.com/assets/bankid/rp/riktlinjer-foer-mobilt-bankid-till-foerlitande-part-1-0-7.pdf

The docs don't explain it that well, but the collect response contains a signature from the client, and a OCSP response by what I'm guessing is the bank which signed the client's certificate. 

> The OCSP 0 response is signed by a certificate that has the same issuer as the certificate being 
> verified (i.e. the BankId).

I think the purpose for this is that it gives the bank power to revoke the user certificate. So the infrastructure in that sense is reliant on both the bank and the BankID backend. I think the bank controls the OCSP stapling, while BankID stands for the authentication infrastructure. 

I found some old documentation of the server architecture for the Norwegian system from 2005:
http://www.eurim.org.uk/activities/pi/BankIDWhitePaper.pdf

So there seems to be the root-CA which is jointly owned by all the banks. Then each bank gets its own level-1 CA signed by the root. 

Question is, do we need to verify these as a merchant? Why would they include them in the response otherwise?

**Comment by Tethik** [comment]
Looking at what the signature contains now. Decodes to XML which contains stuff like certificates etc.

**Comment by Tethik** [comment]
Signature contains an XML document with certificate chain, including customers certificate. OCSP Response contains a OCSP response (duh) made by the bank certificate for the customer in question.

So we could parse and verify that information to really verify the customer in question.

**Comment by hbldh** [comment]
I have never actually decoded the OCSP and studied it, but if it is as you say and it contains the required certificates, nonces to verify, why not do it. 
Does it contain the information that was signed/authenticated as well, or do we have to store that in the BankIDClient for retrieval when COMPLETED is received? Or am I mistaken in my idea that it is needed?

**Comment by Tethik** [comment]
I haven't verified the signatures yet, but it looks like it yes. Here's a raw copy of the signature as xml:
https://gist.githubusercontent.com/Tethik/1f0dcb21b306f1998691/raw/60f97d1a5a759d038514ba4739a637776057d9b9/bankid_signature.xml

I'm guessing **SignatureValue** contains the signature. **bankIdSignedData** the data which was signed. **KeyInfo** is the certificate chain, from root to customer. 

I'm guessing that when using the sign functionality we have to store the data that is to be signed. Or at least a secure-ish checksum of it. Otherwise, how would we know that the customer hasn't tampered with the information before signing it? Alternatively we could put a signature of the request-to-be-signed data inside the **userNonVisibleData** sent to sign and verify that on return.

**Comment by Tethik** [comment]
To clarify, **userNonVisibileData** is sent to the Sign method at the API.

**Comment by hbldh** [comment]
This would be intresting to do, but being on parental leave renders it pretty hopeless to have time to do it. If you feel you have the time and desire to do it, go ahead.

My approach would be to use the **userNonVisibleData** field as a storage of e.g. a SHA256 of the **bankIdSignedData** and verify these upon getting OCSP response. Given that the **userNonVisibleData** never hits the BankID desktop or mobile phone client, but stays on the verified servers.
I am thinking that since we also verify the server's certificates when callng BankID REST API methods, where is the possibility to tamper with the data to sign? The end-user clients *should* not be possible to tamper with?

**Comment by hbldh** [comment]
Accidentally closed it...

**Comment by Tethik** [comment]
I think the purpose is to add an extra layer of security. By verifying the certificate chain and OCSP response we harden the security of the response by verifying against both the bank and bankid organisation. An attacker would have to compromise both. 

Sounds good, except you'd want to sign the userNonVisibleData still with a key used by *us* to prove that we sent it. Otherwise an attacker could just change the SHA256 value.  signature on us has to include some sort of secret. A HMAC with would be more suitable I think. 

If my work decides they want to implement BankID I'll try to implement this functionality. So far I've only prototyped it, I'll likely be waiting on upper management to decide what to do next for a while :\.

**Comment by hbldh** [comment]
PyBankID will not implement this. It can be done according to description below, but it is deemed to be a non-necessary feature for this implementation. Since the *self signed root certificate [...] is delivered to you on request*, I will leave the necessary instructions below for those wanting to verify signatures themselves.

From [BankID Relying Party Guidelines Version: 3.0 (2018-02-16)](https://www.bankid.com/assets/bankid/rp/bankid-relying-party-guidelines-v3.0.pdf):

## 12 Verifying Signatures
The signatures (including the certificates) returned from the service are already verified by the service.

**Note: The Relying Party does not need to verify the signatures**

It is however possible for the Relying Party to verify them. To do that, the following data is needed:
* The `signature` returned from the service. A specification of the content is delivered to you on
request.
* The certificate of the user and intermediate CA:s. These are included in the signature.
* The `ocspResponse` returned from the service.
* The self signed root certificate. This is delivered to you on request.

The following principle is applicable:
1. Verify the `signature`.
2. Verify the certificates in the certificate chain up to the self signed root. Note that certificates may have
expired at the time of verification if it is later than the time of use.
3. Verify the status of the `ocspResponse` to be ok.
4. Verify the signature of the `ocspResponse`.
5. Verify the certificate of the `ocspResponse` signer and that it is issued by the same CA as the user
certificate in question.
6. Verify the nonce included in the `ocspResponse` to be correct by matching it with a hash computed of
the signature. See *completionData for Completed Orders*.
